### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by jchayan** [lsm/micromono#7]
Please update the readme.MD at the Design section, I want to learn a lot more about this.

**Comment by lsm** [comment]
The document will be fully updated when we reach 0.2.0 (pretty close now) as the design is still keep changing dramatically. Thanks!

**Comment by jchayan** [comment]
@lsm Thank you and congratulations for such amazing work, I want to know how to require a local microservice. I tried to import it as a node package, included it in my package.json and then do:

`micromono.require('service');`

But looks like it doesn't discover my services locally. Will this information be included in the design section?

Thanks in advance

**Comment by lsm** [comment]
Thanks for the kind words!

We have a [full example here](https://github.com/lsm/micromono/tree/master/example). You can clone the code and try it. And you can get an idea about how to `require` a service in the example.

Let me know if you run into trouble with the example code.
