### ISSUE TITLE
Services not running

### ISSUE THREAD

**Issue by jchayan** [lsm/micromono#8]
I have an express server running a balancer on port 3000, and a microservice called areabus running on a separate terminal.

My services are located in a folder called ./microservices so I run as follows:

`babel-node index.js --service-dir ./microservices --service areabus`

However I get the following error: 

`TypeError: BaseClass.extend is not a function at exports.singletonify... at ServiceManager.register`

I checked out your code on that function and I apparently made it work by replacing the first line by: 

`var ServiceFactory = singletonify(ServiceClass.extend ? ServiceClass : ServiceClass[name])`
as I noticed that the ServiceClass parameter doesn't contain the `extend` function required in helper.js:15 but the service inside this object, does contain this function.

Is this a bug? Is it related to using the `--service-dir` command line parameter? Or is it a problem on my side?

Thanks in advance

**Comment by lsm** [comment]
It would much easier to identify the problem if you can post the code which can reproduce the error. Thanks!

**Comment by jchayan** [comment]
The service: 

    import { default as Micromono } from 'micromono';
    var micromono = new Micromono();
    var Service = Micromono.Service;

    var areabus = Service.extend({
        packagePath: __dirname,
        baseUrl: '/areabus',
        route: {
            'get::/route/:points': function(req, res) {
                var points = req.params.points;
                console.log(points);
                res.send('Hello, ' + points);
            },
            'get::^/': function(req, res) {
                res.send('Hello');
            }
        },
        init: function() {
            return Promise.resolve();
        }
    });

    export { areabus };

    if (require.main === module) {
        micromono.startService(areabus);
    }

the server:

    var app = express();

    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({ extended: true }));
    app.use(cookieParser());
    app.use(express.static(path.join(__dirname, 'public')));
    app.use(httpLogger);
    app.use('/', router);
    app.use(httpErrorLogger);

    var micromono = new Micromono();

    micromono.startBalancer(app).then(() => {
        logger.info('server booted');
        let server = app.listen(3000, () => {
            logger.info('Listening to port: ' + server.address().port);
        });
    });

As I said, I worked around it as described above, however when I hit the service endpoints I don't get any response.

Thank you for your help!

**Comment by lsm** [comment]
You service code will be compiled to follow ES5 code:

```javascript
'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _micromono = require('micromono');

var _micromono2 = _interopRequireDefault(_micromono);

var micromono = new _micromono2['default']();
var Service = _micromono2['default'].Service;

var areabus = Service.extend({
  name: 'service',
  packagePath: __dirname,
  baseUrl: '/areabus',
  route: {
    'get::/route/:points': function getRoutePoints(req, res) {
      var points = req.params.points;
      console.log(points);
      res.send('Hello, ' + points);
    },
    'get::^/': function get(req, res) {
      res.send('Hello');
    }
  },
  init: function init() {
    return Promise.resolve();
  }
});

exports.areabus = areabus;

if (require.main === module) {
  micromono.startService(areabus);
}

```

The problem code is `exports.areabus = areabus;` which should be `module.exports = areabus`.

Also try run the service standalone with following command:

`DEBUG=micromono* node areabus.js`

That would give you more information.

**Comment by jchayan** [comment]
Perfect, thank you very much sir, seems like Harmony uses the `exports` object instead of `module.exports`, I have a little concern: I see that the micro-service runs an individual server on its own port. My server.js is running on port 3000, I want to use it as an API gateway, so that all incoming requests hitting the gateway point to the micro-service somehow, I'm not sure if I have the clear concepts but I thought this was the default behavior, I can hit the service's routes only through the server that is running on its port. How can I achieve this behavior?

Thank you again.

**Comment by lsm** [comment]
You can try `export default areabus` in ES6. 

Yes, that is correct. The `server.js` is like a gateway. You can start the behind services in a private net work or `127.0.0.1` if you want to hide them from the outside world. When you run your services add an option:

`DEBUG=micromono* node areabus.js -p 9000 --host 127.0.0.1`

More options can be printed by `node areabus.js -h`

**Comment by jchayan** [comment]
Thanks for your support, The problem is that I can't seem to get it working as a gateway, I'm running it in microservices mode like follows:

`DEBUG=micromono* babel-node areabus/index.js`
`DEBUG=micromono* babel-node index.js --service areabus`

It seems to discover the microservice and attach it to the gateway properly:

`micromono:rpc:axon client connected from ....`
But if I issue a GET to: `http://localhost:3000/areabus/route/1`

It catches a 404, which makes me think that the microservices route are not being registered in the gateway for some reason?.

**Comment by lsm** [comment]
Try run balancer using:

`DEBUG=micromono*,express* babel-node index.js --service areabus`

And see what happens in express.

**Comment by jchayan** [comment]
Hello, here's the output http://pastebin.com/t1ZEvM5X

**Comment by lsm** [comment]
Your route won't match your request:
route/:from/:to vs route/1
Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2]
On Mon, Nov 16, 2015 at 12:25 AM, lsm/micromono
<reply@reply.github.com>
wrote:
Hello, here's the output [http://pastebin.com/t1ZEvM5X] http://pastebin.com/t1ZEvM5X [http://pastebin.com/t1ZEvM5X]

—
Reply to this email directly or view it on GitHub
[https://github.com/lsm/micromono/issues/8#issuecomment-156953909] .[https://github.com/notifications/beacon/AAKhR3lXMl4823NURWy6JDtGbv9JTBchks5pGYqLgaJpZM4GgCoB.gif]

**Comment by lsm** [comment]
Can you also upload the output from express after you made the request?

**Comment by jchayan** [comment]
Yes I just corrected my previous answer, I was actually trying with: `http://localhost:3000/areabus/route/1/2`

Here's the output, I'm using winston as logger:

info: HTTP GET /areabus/route/1/2 404 3ms statusCode=404, url=/areabus/route/1/2, host=localhost:3000, connection=keep-alive, accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8, upgrade-insecure-requests=1, user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36, accept-encoding=gzip, deflate, sdch, accept-language=es,en-US;q=0.8,en;q=0.6, cookie=_ga=GA1.1.16639243.1439914558; remember_82e5d2c56bdd0811318f0cf078b78bfc=eyJpdiI6IjlObjZVaTVUMnRZakVvandISEd5Y3c9PSIsInZhbHVlIjoicmdhQUpHQWo3eHJKYmFPUnA0RXRuaVpzOEFHZWhEK0pLRmI4eDNvV0tvNjFKYzRcL1FQSDl4RFNkREY5SW01N0hjeVU3MWVFV2NESUZvVEk2bmhBaURxdTlHbE1zWmF6cEpvU2s0XC9jcVNCND0iLCJtYWMiOiJlODI2NmFiM2IyZGY3YTY4ZmEyYzZlZDhjOWYxMjc2MTM4ZDAwZTIzMzcyYTczMjJiOGYxNWJlMWQyNTAwOGY5In0%3D, method=GET, httpVersion=1.1, originalUrl=/areabus/route/1/2, , responseTime=3

**Comment by lsm** [comment]
I can't reproduce your error. I added a url similar to what you have. Please checkout the master branch and try if that works for you.

**Comment by jchayan** [comment]
Well I sorted it out, I was using an error handler in the server.js, just deleted it and worked. Thanks for the help and keep up such amazing work!

**Comment by lsm** [comment]
You are welcome. 

You can mount the error middleware in the promise return by `startBalancer`.
